### ISSUE TITLE
Add more examples

### ISSUE THREAD

**Issue by ainsleyclark** [ashbuilds/payload-ai#54]
Hey there,

Thanks for this plugin 🙏 

I'm wondering if it's possible to enhance the documentation/readme with a wider range of examples for fields, prompts etc. It's not 100% clear how to:

- Add it to the `textarea` and `upload` fields.
- Provide the fields that each collection should use, I.e I want to disable use for specific fields.\

Also, is it possible to limit the prompt editing on conditions or provide prompts outside of the editor for the dev only? I.e, access control (admins should only be able to create prompts). I

Thanks!

**Comment by ashbuilds** [comment]
Hi @ainsleyclark! I’ve added a detailed setup guide covering all the field configurations. I’m closing this issue now, but please feel free to share your feedback if you come across anything. Thanks!
